### PR TITLE
Add learning task list for evaluation projects.

### LINKED ISSUE #42: Parse and display results of learningTaskAndExamList
**Describe the solution you'd like**
Parse and display the results of learningTaskAndExamList from GetDynamicScoreDetail.
The tasks should be a list under the evaluation project.

**Describe alternatives you've considered**
This method should be faster than fetching all tasks (no DDoSing) and should be easier to implement.

**Additional context**
It seems like this feature was recently added to xiaobao.

### PR DESCRIPTION
**Pull request by hey2022**
This should parse and display the individual tasks that make up an evaluation project and their proportion. It is useful for determining which task is influencing a subject score. Closes #42

### CODE REVIEW

**Comment by hey2022** [comment]
Waiting on #57

**Review by wusitee — APPROVED** [review]
LGTM.

**Review by lanbinleo — APPROVED** [review]
LGTM

**Comment by wusitee** [comment]
Bro, don't want to resolve conflicts?

**Review by aulimaru — APPROVED** [review]
lgtm, i'll resolve conflicts

**Comment by hey2022** [comment]
This doesn't follow formatting output after #61 got merged.

**Comment by hey2022** [comment]
It also has bugs with nested evaluation project.

**Comment by aulimaru** [comment]
._.

**Comment by aulimaru** [comment]
bro got scammed by wusitee

**Pull request merged**
