### PR TITLE
Add self updater

### LINKED ISSUE #59: Add Version Check Feature After Score Calculation
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't know if there is a new version of the software available. This can lead to missing out on important updates and improvements.

**Describe the solution you'd like**
I would like the software to check for the latest version after each score calculation. Specifically, it should request a file from GitHub that contains the version number. If the latest version number is greater than the local version number, the software should notify the user that a new version is available. In the future, we might add a one-click upgrade feature. Given that more students are using this program, we should start making it more user-friendly.

**Describe alternatives you've considered** 
An alternative solution could be to manually check for updates on the GitHub repository, but this is less convenient and can be easily overlooked by users.

### PR DESCRIPTION
**Pull request by hey2022**
Uses the crate self_update to automatically check for and update tls-xb.

Closes #59.

I can't get the updated binary to run on my computer when testing.
Can someone reproduce?

### CODE REVIEW

**Comment by wusitee** [comment]
It seems to work well on my computer.
```sh
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v0.3.5
Checking latest released version... v0.3.6
New release found! v0.3.5 --> v0.3.6
New release is compatible

github release status:
  * Current exe: "/home/wste/code/rust/tls-xb/target/debug/tls-xb"
  * New exe release: "tls-xb-x86_64-unknown-linux-gnu.tar.xz"
  * New exe download url: "https://api.github.com/repos/hey2022/tls-xb/releases/assets/212553928"

The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] y
Downloading...
[00:00:01] [========================================] 2.65 MiB/2.65 MiB (0s) Done                                                               Extracting archive... Done
Replacing binary file... Done
Update status: `0.3.6`!
on  HEAD (5d9305e) [$] is 📦 v0.3.5 via 🦀 v1.83.0 took 1m58s 
tls-xb ❯ tls-xb -V
tls-xb 0.3.6
```

**Comment by wusitee** [comment]
The file downloaded is compressed. The update function should decompress it and extract binary from it.

**Comment by wusitee** [comment]
Don't forget to change the update part in README.md

**Comment by wusitee** [comment]
Tested in my fork, it can't work, here is the log:
```sh
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v0.4.0
Checking latest released version... v0.4.1
New release found! v0.4.0 --> v0.4.1
New release is compatible

tls-xb release status:
  * Current exe: "/home/wste/.cargo/bin/tls-xb"
  * New exe release: "tls-xb-x86_64-unknown-linux-gnu.tar.gz"
  * New exe download url: "https://api.github.com/repos/wusitee/tls-xb/releases/assets/213057954"

The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] Y
Downloading...
[00:00:01] [========================================] 3.88 MiB/3.88 MiB (0s) Done   
Extracting archive... UpdateError: Could not find the required path in the archive: "tls-xb"
```

**Review by lanbinleo — APPROVED** [review]
Seems good, but I have no idea of rust's self update. Please double check the code.

**Comment by hey2022** [comment]
released

**Pull request closed without merging**
